name: Caller Wfl
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version for current release'
        required: true
        type: string
#env:
#  USERNAME: "VishnuPratapBankii"
#  TOKEN: ${{secrets.USER_TOKEN}}

jobs:
  
  call-the-deploy-wfl:
    uses: VishnuPratapBankiOrg/called/.github/workflows/called.yaml@main
    permissions:
      contents: write
    with:
      version: ${{inputs.version}}
    secrets:
      MY_TOKEN: ${{secrets.MY_TOKEN}}
      USER_FINE: ${{secrets.USER_FINE}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}


